on: [push]

jobs:
  publish:
    name: Publish

    runs-on: docker
    container:
      image: node:16-bullseye
    defaults:
      run:
        shell: bash -e {0}

    permissions:
      contents: read
      deployments: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: https://github.com/pnpm/action-setup@v3.0.0
        with:
          version: 8

      - name: Configure Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build app
        working-directory: app
        run: |
          RAW_COMMIT=$(git rev-parse HEAD)

          export VITE_GIT_BRANCH=$(git branch --show-current)
          export VITE_GIT_COMMIT=${RAW_COMMIT:0:7}

          echo "branch: $VITE_GIT_BRANCH; commit: $VITE_GIT_COMMIT"
          pnpm run build:desktop

      - name: Publish to Cloudflare Pages
        uses: https://github.com/cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref_name == 'trunk' && 'main' || github.ref_name }}
          projectName: skeetdeck
          workingDirectory: app
          directory: desktop/dist
